// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice =
  | ComparisonSectionSlice
  | ReviewsSliderSlice
  | FaqSectionSlice
  | HistorySectionSlice
  | StepsSectionSlice
  | CardsSectionSlice
  | InfoTextSectionSlice
  | MainSectionSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * OG Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never>;

  /**
   * Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes = PageDocument | SettingsDocument;

/**
 * Item in *CardsSection → Default → Primary → Card*
 */
export interface CardsSectionSliceDefaultPrimaryCardItem {
  /**
   * icon field in *CardsSection → Default → Primary → Card*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: insurance
   * - **API ID Path**: cards_section.default.primary.card[].icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon: prismic.SelectField<
    "insurance" | "safe" | "smile" | "free" | "time",
    "filled"
  >;

  /**
   * Title field in *CardsSection → Default → Primary → Card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards_section.default.primary.card[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *CardsSection → Default → Primary → Card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards_section.default.primary.card[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *CardsSection → Default → Primary*
 */
export interface CardsSectionSliceDefaultPrimary {
  /**
   * Card field in *CardsSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cards_section.default.primary.card[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  card: prismic.GroupField<Simplify<CardsSectionSliceDefaultPrimaryCardItem>>;
}

/**
 * Default variation for CardsSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CardsSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CardsSection*
 */
type CardsSectionSliceVariation = CardsSectionSliceDefault;

/**
 * CardsSection Shared Slice
 *
 * - **API ID**: `cards_section`
 * - **Description**: CardsSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsSectionSlice = prismic.SharedSlice<
  "cards_section",
  CardsSectionSliceVariation
>;

/**
 * Item in *ComparisonSection → Default → Primary → Items*
 */
export interface ComparisonSectionSliceDefaultPrimaryItemsItem {
  /**
   * title field in *ComparisonSection → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison_section.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * TMS field in *ComparisonSection → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: TMS (Transcranial Magnetic Stimulation)
   * - **API ID Path**: comparison_section.default.primary.items[].tms
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tms: prismic.KeyTextField;

  /**
   * Spravato field in *ComparisonSection → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Spravato (Esketamine)
   * - **API ID Path**: comparison_section.default.primary.items[].spravato
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  spravato: prismic.KeyTextField;

  /**
   * IV IM field in *ComparisonSection → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: IV/IM Ketamine Infusions
   * - **API ID Path**: comparison_section.default.primary.items[].iv_im
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  iv_im: prismic.KeyTextField;
}

/**
 * Primary content in *ComparisonSection → Default → Primary*
 */
export interface ComparisonSectionSliceDefaultPrimary {
  /**
   * Pre Heading field in *ComparisonSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison_section.default.primary.pre_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  pre_heading: prismic.RichTextField;

  /**
   * Heading field in *ComparisonSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * TMS Title field in *ComparisonSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison_section.default.primary.tms_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tms_title: prismic.KeyTextField;

  /**
   * Spravato Title field in *ComparisonSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison_section.default.primary.spravato_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  spravato_title: prismic.KeyTextField;

  /**
   * IV IM Title field in *ComparisonSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison_section.default.primary.iv_im_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  iv_im_title: prismic.KeyTextField;

  /**
   * Items field in *ComparisonSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: comparison_section.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<
    Simplify<ComparisonSectionSliceDefaultPrimaryItemsItem>
  >;
}

/**
 * Default variation for ComparisonSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ComparisonSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ComparisonSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ComparisonSection*
 */
type ComparisonSectionSliceVariation = ComparisonSectionSliceDefault;

/**
 * ComparisonSection Shared Slice
 *
 * - **API ID**: `comparison_section`
 * - **Description**: ComparisonSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ComparisonSectionSlice = prismic.SharedSlice<
  "comparison_section",
  ComparisonSectionSliceVariation
>;

/**
 * Item in *FaqSection → Default → Primary → List*
 */
export interface FaqSectionSliceDefaultPrimaryListItem {
  /**
   * Label field in *FaqSection → Default → Primary → List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.default.primary.list[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * text field in *FaqSection → Default → Primary → List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.default.primary.list[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Primary content in *FaqSection → Default → Primary*
 */
export interface FaqSectionSliceDefaultPrimary {
  /**
   * Heading field in *FaqSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * List field in *FaqSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.default.primary.list[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  list: prismic.GroupField<Simplify<FaqSectionSliceDefaultPrimaryListItem>>;
}

/**
 * Default variation for FaqSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FaqSection*
 */
type FaqSectionSliceVariation = FaqSectionSliceDefault;

/**
 * FaqSection Shared Slice
 *
 * - **API ID**: `faq_section`
 * - **Description**: FaqSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSectionSlice = prismic.SharedSlice<
  "faq_section",
  FaqSectionSliceVariation
>;

/**
 * Item in *HistorySection → Default → Primary → List*
 */
export interface HistorySectionSliceDefaultPrimaryListItem {
  /**
   * year field in *HistorySection → Default → Primary → List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: history_section.default.primary.list[].year
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  year: prismic.KeyTextField;

  /**
   * Text field in *HistorySection → Default → Primary → List*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: history_section.default.primary.list[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Link Title field in *HistorySection → Default → Primary → List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: history_section.default.primary.list[].link_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_title: prismic.KeyTextField;

  /**
   * Link Address field in *HistorySection → Default → Primary → List*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: history_section.default.primary.list[].link_address
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_address: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *HistorySection → Default → Primary*
 */
export interface HistorySectionSliceDefaultPrimary {
  /**
   * Heading field in *HistorySection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: history_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * List field in *HistorySection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: history_section.default.primary.list[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  list: prismic.GroupField<Simplify<HistorySectionSliceDefaultPrimaryListItem>>;

  /**
   * Button Text field in *HistorySection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: history_section.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *HistorySection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: history_section.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for HistorySection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HistorySectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HistorySectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HistorySection*
 */
type HistorySectionSliceVariation = HistorySectionSliceDefault;

/**
 * HistorySection Shared Slice
 *
 * - **API ID**: `history_section`
 * - **Description**: HistorySection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HistorySectionSlice = prismic.SharedSlice<
  "history_section",
  HistorySectionSliceVariation
>;

/**
 * Primary content in *InfoSection → Default → Primary*
 */
export interface InfoTextSectionSliceDefaultPrimary {
  /**
   * Pre Heading field in *InfoSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_text_section.default.primary.pre_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  pre_heading: prismic.RichTextField;

  /**
   * Heading field in *InfoSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_text_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *InfoSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_text_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Button Text field in *InfoSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_text_section.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *InfoSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: info_text_section.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for InfoSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoTextSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<InfoTextSectionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *InfoSection → Left Photo → Primary*
 */
export interface InfoTextSectionSliceLeftPhotoPrimary {
  /**
   * image field in *InfoSection → Left Photo → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: info_text_section.leftPhoto.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Pre Heading field in *InfoSection → Left Photo → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_text_section.leftPhoto.primary.pre_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  pre_heading: prismic.RichTextField;

  /**
   * Heading field in *InfoSection → Left Photo → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_text_section.leftPhoto.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *InfoSection → Left Photo → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_text_section.leftPhoto.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Button Text field in *InfoSection → Left Photo → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_text_section.leftPhoto.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *InfoSection → Left Photo → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: info_text_section.leftPhoto.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Left Photo variation for InfoSection Slice
 *
 * - **API ID**: `leftPhoto`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoTextSectionSliceLeftPhoto = prismic.SharedSliceVariation<
  "leftPhoto",
  Simplify<InfoTextSectionSliceLeftPhotoPrimary>,
  never
>;

/**
 * Slice variation for *InfoSection*
 */
type InfoTextSectionSliceVariation =
  | InfoTextSectionSliceDefault
  | InfoTextSectionSliceLeftPhoto;

/**
 * InfoSection Shared Slice
 *
 * - **API ID**: `info_text_section`
 * - **Description**: InfoTextSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoTextSectionSlice = prismic.SharedSlice<
  "info_text_section",
  InfoTextSectionSliceVariation
>;

/**
 * Item in *MainSection → Default → Primary → Options*
 */
export interface MainSectionSliceDefaultPrimaryOptionsItem {
  /**
   * Item field in *MainSection → Default → Primary → Options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: main_section.default.primary.options[].item
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item: prismic.KeyTextField;
}

/**
 * Primary content in *MainSection → Default → Primary*
 */
export interface MainSectionSliceDefaultPrimary {
  /**
   * Heading field in *MainSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: main_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *MainSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: main_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Text Background field in *MainSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: main_section.default.primary.text_background
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  text_background: prismic.ImageField<never>;

  /**
   * Main image field in *MainSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: main_section.default.primary.main_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  main_image: prismic.ImageField<never>;

  /**
   * Options field in *MainSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: main_section.default.primary.options[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  options: prismic.GroupField<
    Simplify<MainSectionSliceDefaultPrimaryOptionsItem>
  >;

  /**
   *  Button text field in *MainSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: main_section.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *MainSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: main_section.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for MainSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MainSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MainSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MainSection*
 */
type MainSectionSliceVariation = MainSectionSliceDefault;

/**
 * MainSection Shared Slice
 *
 * - **API ID**: `main_section`
 * - **Description**: MainSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MainSectionSlice = prismic.SharedSlice<
  "main_section",
  MainSectionSliceVariation
>;

/**
 * Item in *ReviewsSlider → Default → Primary → Items*
 */
export interface ReviewsSliderSliceDefaultPrimaryItemsItem {
  /**
   * photo field in *ReviewsSlider → Default → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews_slider.default.primary.items[].photo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  photo: prismic.ImageField<never>;

  /**
   * Text field in *ReviewsSlider → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews_slider.default.primary.items[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * Full Name field in *ReviewsSlider → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews_slider.default.primary.items[].full_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  full_name: prismic.KeyTextField;
}

/**
 * Primary content in *ReviewsSlider → Default → Primary*
 */
export interface ReviewsSliderSliceDefaultPrimary {
  /**
   * Heading field in *ReviewsSlider → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews_slider.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Items field in *ReviewsSlider → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews_slider.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<
    Simplify<ReviewsSliderSliceDefaultPrimaryItemsItem>
  >;
}

/**
 * Default variation for ReviewsSlider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReviewsSliderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ReviewsSliderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ReviewsSlider*
 */
type ReviewsSliderSliceVariation = ReviewsSliderSliceDefault;

/**
 * ReviewsSlider Shared Slice
 *
 * - **API ID**: `reviews_slider`
 * - **Description**: ReviewsSlider
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReviewsSliderSlice = prismic.SharedSlice<
  "reviews_slider",
  ReviewsSliderSliceVariation
>;

/**
 * Item in *StepsSection → Default → Primary → steps*
 */
export interface StepsSectionSliceDefaultPrimaryStepsItem {
  /**
   * Label field in *StepsSection → Default → Primary → steps*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: steps_section.default.primary.steps[].label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.RichTextField;

  /**
   * Description field in *StepsSection → Default → Primary → steps*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: steps_section.default.primary.steps[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *StepsSection → Default → Primary → steps*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: steps_section.default.primary.steps[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *StepsSection → Default → Primary → Badges*
 */
export interface StepsSectionSliceDefaultPrimaryBadgesItem {
  /**
   * Step Index field in *StepsSection → Default → Primary → Badges*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: steps_section.default.primary.badges[].step_index
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  step_index: prismic.NumberField;

  /**
   * Icon field in *StepsSection → Default → Primary → Badges*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: steps_section.default.primary.badges[].icon
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  icon: prismic.KeyTextField;

  /**
   * Text field in *StepsSection → Default → Primary → Badges*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: steps_section.default.primary.badges[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Primary content in *StepsSection → Default → Primary*
 */
export interface StepsSectionSliceDefaultPrimary {
  /**
   * Title field in *StepsSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: steps_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * steps field in *StepsSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: steps_section.default.primary.steps[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  steps: prismic.GroupField<Simplify<StepsSectionSliceDefaultPrimaryStepsItem>>;

  /**
   * Badges field in *StepsSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: steps_section.default.primary.badges[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  badges: prismic.GroupField<
    Simplify<StepsSectionSliceDefaultPrimaryBadgesItem>
  >;

  /**
   * Action Title field in *StepsSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: steps_section.default.primary.action_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  action_title: prismic.RichTextField;

  /**
   * Action Desctiption field in *StepsSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: steps_section.default.primary.action_desctiption
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  action_desctiption: prismic.RichTextField;

  /**
   * Action Button Text field in *StepsSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: steps_section.default.primary.action_button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  action_button_text: prismic.KeyTextField;

  /**
   * Action Button Link field in *StepsSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: steps_section.default.primary.action_button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  action_button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for StepsSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StepsSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StepsSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *StepsSection*
 */
type StepsSectionSliceVariation = StepsSectionSliceDefault;

/**
 * StepsSection Shared Slice
 *
 * - **API ID**: `steps_section`
 * - **Description**: StepsSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StepsSectionSlice = prismic.SharedSlice<
  "steps_section",
  StepsSectionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      AllDocumentTypes,
      CardsSectionSlice,
      CardsSectionSliceDefaultPrimaryCardItem,
      CardsSectionSliceDefaultPrimary,
      CardsSectionSliceVariation,
      CardsSectionSliceDefault,
      ComparisonSectionSlice,
      ComparisonSectionSliceDefaultPrimaryItemsItem,
      ComparisonSectionSliceDefaultPrimary,
      ComparisonSectionSliceVariation,
      ComparisonSectionSliceDefault,
      FaqSectionSlice,
      FaqSectionSliceDefaultPrimaryListItem,
      FaqSectionSliceDefaultPrimary,
      FaqSectionSliceVariation,
      FaqSectionSliceDefault,
      HistorySectionSlice,
      HistorySectionSliceDefaultPrimaryListItem,
      HistorySectionSliceDefaultPrimary,
      HistorySectionSliceVariation,
      HistorySectionSliceDefault,
      InfoTextSectionSlice,
      InfoTextSectionSliceDefaultPrimary,
      InfoTextSectionSliceLeftPhotoPrimary,
      InfoTextSectionSliceVariation,
      InfoTextSectionSliceDefault,
      InfoTextSectionSliceLeftPhoto,
      MainSectionSlice,
      MainSectionSliceDefaultPrimaryOptionsItem,
      MainSectionSliceDefaultPrimary,
      MainSectionSliceVariation,
      MainSectionSliceDefault,
      ReviewsSliderSlice,
      ReviewsSliderSliceDefaultPrimaryItemsItem,
      ReviewsSliderSliceDefaultPrimary,
      ReviewsSliderSliceVariation,
      ReviewsSliderSliceDefault,
      StepsSectionSlice,
      StepsSectionSliceDefaultPrimaryStepsItem,
      StepsSectionSliceDefaultPrimaryBadgesItem,
      StepsSectionSliceDefaultPrimary,
      StepsSectionSliceVariation,
      StepsSectionSliceDefault,
    };
  }
}
